name: Deploy Laravel App to Rumahweb

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        composer install --no-dev --optimize-autoloader
        npm install && npm run production || true

    - name: Deploy to Rumahweb
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        ftp-server: "ftp.inviteles.store"
        ftp-username: "app@inviteles.store"
        ftp-password: "@WW^h]mBwC5k"
        local-dir: ./ # Path of your Laravel project
        server-dir: /public_html/app.inviteles.store/ # Path in Rumahweb server
